config/routes.rb
Rails.application.routes.draw do
  resources :sessions
  resources :users

  get 'welcome/index'
  
  get 'login', {to: 'sessions#new', as: 'login'}
  get 'logout', {to: 'sessions#destroy', as: 'logout'}
  get 'signup', {to: 'sessions#create', as: 'signup'}

  root 'welcome#index'

  resources :articles
  resources :categories

end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :user
	
	validate :title, presence: true
	validate :content, presence: true
	validate :categories, presence: true
	
	has_many :article_categories
	has_many :categories, through: :article_categories
end

app/models/article_category.rb
class ArticleCategory < ActiveRecord::Base
	belongs_to :article
	belongs_to :category	
end

app/models/category.rb
class Category < ActiveRecord::Base
	validate :name, presence: true
	validate :name, uniqueness: true
	has_many :article_categories
	has_many :articles, through: :article_categories
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	validates :name, presence: true
	validates :email, presence: true
	validates_uniqueness_of :email
	has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :get_categories

  def authorize
    redirect_to login_url, alert: "Not authorized" if current_user.nil?
  end

  private
  	def get_categories
  		@categories = Category.order(name: :asc)
  	end

  	def current_user
  		@current_user ||= User.find(session[:user_id]) if session[:user_id] 
  	end

  	helper_method :current_user
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	before_filter :authorize, only: [:new]

	def index
		@articles = Article.order({title: :asc, updated_at: :desc}).limit(25)
	end

	def show
		@article = Article.find(params[:id])
	end

	def new
		@article = Article.new
	end

	def edit
		@article = Article.find(params[:id])	
	end

	def create
		@article = Article.new(article_params)
		if @article.save
			redirect_to @article
		else
			render "new"
		end
	end

	def update
		@article = Article.find(params[:id])

		if @article.update(article_params)
			redirect_to @article
		else
			render "update", flash: "error of some kind"
		end
	end

	private

		def article_params
			params.require(:article).permit(:title, :content, :category_ids => [])
		end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	
	def index
		@categories = Category.order(name: :asc)
	end

	def show
		@category = Category.find(params[:id])
	end

	def new
		@category = Category.new
	end

	def edit
		@category = Category.find(params[:id])
		@articles = Article.where(category_id: params[:id])
	end


	def create
		@category = Category.new(category_params)
		if (@category.save)
			redirect_to @category
		else
			render "new"
		end

	end

	private

		def category_params
			params.require(:category).permit(:id, :name)
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def create
  	user = User.find_by_email(params[:email])
  	if user && user.authenticate(params[:password])
  		session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in"
  	else
  		flash.now.alert = "Invalid login"
  		render "new"
  	end

  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			redirect_to root_url, notice: "Thank you for signing up!"
		else
			render "new"
		end
	end

	private
		def user_params
			params.require(:user).permit(:email, :name, :password, :password_confirmation)
		end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  	@recentArticles = Article.order(created_at: :desc).limit(5)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>

	<div class="control-group">
		<%= f.label :title %>
		<div class="controls">
			<%= f.text_field :title %>
		</div>
	</div>

	<div class="control-group">
		<%= f.label :content %>
		<div class="controls">
			<%= f.text_area :content, rows: "20" , cols: "100" %>
		</div>
	</div>

	<div class="control-group">
		<%= f.label "File under at least one category" %>
		<% Category.all.order(name: :asc).each do |category| %>
			<div>
				<%= check_box_tag "article[category_ids][]", category.id %>
				<%= category.name %>
			</div>
		<% end %>
	</div>

	<div class="form-actions">
		<%= f.submit nil %>
		<%= link_to "Cancel", articles_path %>
	</div>

<% end %>

app/views/articles/edit.html.erb
<h1>EDIT  <%= @article.title %> </h1> 

<%= render :partial => 'form' %>

app/views/articles/index.html.erb
<h1>This is the index view for Articles</h1>
Create new article here: <%= link_to "New Article", new_article_path %>
<% @articles.each do |article| %>
<div>
<h3><%= link_to article.title, article %></h3>

	<p>Published on <%= article.created_at.strftime('%b %d, %y')%></p>
	<p>Filed under 

	<% @categories = article.categories %>
	<% @categories.each do |cat| %>
		<%= cat.name %>
	<% end %>
	</p>
	<p>
	<%= truncate(article.content, {length: 200}) %>
	</p>


<% end %>

app/views/articles/new.html.erb
<h1>Write and Publish a New Article</h1>
  <% if @article.errors.any? %>
  <div class="error_messages">
      <h2>You're missing some fields</h2>
      <ul>
        <% @article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= render :partial => 'form' %>

app/views/articles/show.html.erb
<h3><%= @article.title %></h3>
Filed under:
<p>
<% @article.categories.each do |c| %>

<%= link_to c.name, category_path(c) %>

<% end %>

</p>
<%= link_to "Edit Article", edit_article_path %>
<p><%= @article.content %></p>

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>

	<div class="control-group">
		<%= f.label :title %>
		<div class="controls">
			<%= f.text_field :title %>
		</div>
	</div>

	<div class="control-group">
		<%= f.label :content %>
		<div class="controls">
			<%= f.text_field :content, rows: "20" , cols: "100" %>
		</div>
	</div>

	<div class="control-group">
		<%= f.label "File under at least one category" %>
		<% Category.all.order(name: :asc).each do |category| %>
			<div>
				<%= check_box_tag "article[category_ids][]", category.id %>
				<%= category.name %>
			</div>
		<% end %>
	</div>

	<div class="form-actions">
		<%= f.submit nil %>
		<%= link_to "Cancel", articles_path %>
	</div>

<% end %>

app/views/categories/edit.html.erb
<%= @category.name %> !!

app/views/categories/index.html.erb
 <p><%= link_to "New", new_category_path %></p>

<% @categories.each do |c| %>

<p><%= c.name %> <%= link_to "Edit", edit_category_path(c) %></p>

<% end %>

app/views/categories/show.html.erb
<h1><%= @category.name %> Category </h1>

<h3>Articles:</h3>

<% @category.articles.each do |a| %>

  <p><%= link_to a.title, article_path(a) %></p>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wikiful</title>
  <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <%= link_to "Wikiful", root_path, :class => "brand" %>
        
					<div class='session-controls'> 
            <div class="btn-group">
            	<% if current_user %>
              	Logged in as <%= current_user.email %>
              	<p><%= link_to "Log Out", session_path("current"), method: 'delete' %></p>
            	<% else %>
	              <%= link_to "Sign Up", new_user_path, :class => "btn btn-default" %>
	              <%= link_to "Log In", new_session_path, :class => "btn btn-default" %>
       				<% end %>
            </div>
         </div>

      </div>
    </div>
  </div>


  <div class="container">
    <div class="row">

  

      	<div class="col-lg-3 sidebar">
      		
      		<div class="flash-notices">
	      		<% flash.each do |name, msg| %>
	        		<%= content_tag :div, msg, id: "flash_#{name}" %>
	      		<% end %>
      		</div>

	      	<div class="my-wiki-site">
		      	<h4>My Wikiful</h4>
		      	<ul>
		      		<li><%= link_to "Write new Article", new_article_path %></li>
		      	</ul>
	      	</div>

	      	<div class="categories-sidebar">
	      	<h4>Categories</h4>
	    			<ul>
	    				<% @categories.each do |cat| %>
		      			<li><%= link_to cat.name, cat %></li>
	    				<% end %>
						</ul>
	      	</div>
	      	<div class="about">
						<h4>About Wikiful</h4>
						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium architecto earum neque perspiciatis quia animi debitis quod repellat vitae explicabo. Sapiente aliquam.</p>
	      	</div>

      	</div>

      	<div class="col-lg-9"><%= yield %></div>

      </div>
    </div> 
</body>
</html>

app/views/users/new.html.erb
<h1> Signup </h1>

<%= form_for @user do |f| %>

	<% if @user.errors.any? %>
		<div class="error_messages">
			<h2>Form is invalid</h2>
				<ul>
				<% @user.errors.full_messages do |error| %>
					<li><%= error %></li>
					<% end %>
				</ul>
		</div>
	<% end %>

	<div class="field">
		<%= f.label :name %>
		<%= f.text_field :name %>
	</div>

	<div class="field">
		<%= f.label :email %>
		<%= f.text_field :email %>
	</div>

	<div class="field">
		<%= f.label :password %>
		<%= f.password_field :password %>
	</div>

	<div class="field">
		<%= f.label :password_confirmation %>
		<%= f.password_field :password_confirmation %>
	</div>

	<div class="form-actions">
		<%= f.submit %> 
	</div>

<% end %>

app/views/welcome/index.html.erb
<h1>Welcome</h1>
<p>Welcome to the wonderful world of WikiFul! Here are the latest articles:</p>
<% @recentArticles.each do |a| %>

<p><b><%= link_to a.title, a %></b> Created: <%= a.created_at %></p>
<p><%=truncate(a.content, length: 200)%></p>

<% end %>